groups:
- name: football_guess_who_alerts
  rules:
  - alert: HighErrorRate
    expr: rate(backend_error_total[5m]) > 1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 1 per second for more than 2 minutes"

  - alert: APIHighResponseTime
    expr: backend_http_request_duration_seconds{quantile="0.95"} > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Slow API response time detected"
      description: "95th percentile of API response time is above 500ms for more than 5 minutes"

  - alert: BackendServiceDown
    expr: up{job="backend"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Backend service is down"
      description: "Backend service has been down for more than 1 minute"

  - alert: DatabaseServiceDown
    expr: up{job="postgres-exporter"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Database service is down"
      description: "PostgreSQL database has been down for more than 1 minute"

  - alert: RedisServiceDown
    expr: up{job="redis-exporter"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis service is down"
      description: "Redis cache has been down for more than 1 minute"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 5 minutes"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 5 minutes"

  - alert: LowDiskSpace
    expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 15
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space detected"
      description: "Less than 15% disk space available for more than 5 minutes"

  - alert: HighGameCreationRate
    expr: rate(backend_game_created_total[5m]) > 5
    for: 5m
    labels:
      severity: info
    annotations:
      summary: "High game creation rate"
      description: "More than 5 games created per second for 5 minutes, consider adding more resources" 